quiet: false
disable-version-string: true
mockname: "{{.InterfaceName}}"
filename: "{{.MockName}}.go"
outpkg: "{{.PackageName}}"
with-expecter: true
packages:
  github.com/sattellite/bcdb/compute:
    config:
      dir: "compute/mocks"
    interfaces:
      Computer:

  github.com/sattellite/bcdb/storage:
    config:
      dir: "storage/mocks"
    interfaces:
      Engine:
