version: '3'

tasks:
  run:
    cmds:
      - go mod tidy
      - go run cmd/bcdb/main.go
  lint:
    cmds:
      - golangci-lint --version
      - golangci-lint run ./...
  test:
    cmds:
      - go test -race -v ./...
  mocks:
    cmds:
      - mockery --version || go install github.com/vektra/mockery/v2@latest
      - mockery
