version: '3'

tasks:
  run:
    cmds:
      - go mod tidy
      - go run cmd/bcdb/main.go
  lint:
    cmds:
      - golangci-lint --version
      - golangci-lint run ./...
  test:
    cmds:
      - go test -race -v ./...
